# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-04 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
